In [1]:
import pandas as pd
import numpy as np
#from feature_generators import TS_feature_generator_functions as fg
from timeit import default_timer as dt
from datetime import datetime
import re
from sklearn.externals import joblib
from time import time
from collections import Counter

In [2]:
from sklearn.metrics import accuracy_score

In [3]:
pd.set_option('display.max_columns', None)
%pylab inline

Populating the interactive namespace from numpy and matplotlib


/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['datetime']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [4]:
data_dir = '/home/flowcast/data/python/data_validate_180315/'

In [5]:
ls /home/flowcast/data/python/data_validate_180315/

all_prod_180319.csv           data_3NF_180316_IFNS.csv
all_prod_validate_180319.csv  data_3NF_180316_LBDS.csv
buyer_supplier_3m.csv         data_3NF_180316_LRRP.csv
buyer_supplier_6m.csv         data_3NF_180316_PSHP.csv
buyer_supplier_all.csv        data_3NF_180316_RSRV.csv
buyer_supplier_prevyr.csv     data_3NF_180316_TRDS.csv
cast_columns_template.csv     data_CG.csv
ccy_features_vector.csv       data_for_model.csv
ccy_features_vol.csv          data_for_model.zip
client_3m.csv                 dr_logreg_scores_180223.csv
client_6m.csv                 dr_rf_preds.csv
client_all.csv                LD_logreg_scores_180223.csv
client_prevyr.csv             ld_rf_preds.csv
data_3NF_180316_BATB.csv      lr_dr_180223.joblib
data_3NF_180316_BDBR.csv      lr_ld_180223.joblib
data_3NF_180316_ECIF.csv      minmaxscaler_180223.pkl
data_3NF_180316_ECPR.csv      rf_dr_180223.joblib
data_3NF_180316_IFNB.csv      rf_ld_180223.joblib


In [6]:
data = pd.read_csv(data_dir+'data_for_model.csv')
data.head()


/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


cty_code            doc_id  supplier_id     buyer_id doc_type_code  \
0       AE  RFHLM9WX4V-89034    100369293  100244505.0           INV   
1       AE  V5HKSF85PW-36933    100369293  100244505.0           INV   
2       CN   52HNXCS9NQ-6901    100399400  100310713.0           INV   
3       CN   52HNXCS9NQ-6902    100399400  100310713.0           INV   
4       CN   52HNXCS9NQ-6968    100399400  100310713.0           INV   

      deal_id fin_flag      rec_id    doc_date doc_ccy_code  doc_ccy_amt  \
0  TF123BF562        Y  6728531788  2017-03-24          USD    113268.50   
1  TF123BF144        Y   783293897  2017-03-10          USD    106717.15   
2  TF675BK822        Y  6765119598  2017-03-14          CNY    101409.08   
3  TF675BK822        Y  6765119600  2017-03-20          CNY    197106.76   
4  TF675BK822        Y  6745980446  2017-03-15          CNY    101536.00   

   tenor     tenor_start_date    due_date  grace_period maturity_date  \
0     45  2017-03-24 00:00:00  2017-05-08             0    2017-05-08   
1     45  2017-03-10 00:00:00  2017-04-24             0    2017-04-24   
2     30  2017-03-14 00:00:00  2017-04-13           158    2017-09-18   
3     24  2017-03-20 00:00:00  2017-04-13           158    2017-09-18   
4     29  2017-03-15 00:00:00  2017-04-13           158    2017-09-18   

  fin_tenor_start_date  fin_tenor  to_seq_no  from_seq_no pymt_ccy_code  \
0  2017-03-25 00:00:00       44.0       37.0            1           USD   
1  2017-03-11 00:00:00       44.0       29.0            1           USD   
2  2017-04-10 00:00:00      161.0      116.0            1           CNY   
3  2017-04-10 00:00:00      161.0      116.0            1           CNY   
4  2017-04-10 00:00:00      161.0      116.0            1           CNY   

   pymt_alloc_amt fin_ccy_code  fin_ccy_cp_alloc_amt  fin_ccy_ncp_alloc_amt  \
0       113268.50          USD                   0.0              113268.50   
1       106717.15          USD                   0.0              106717.15   
2       101409.08          CNY                   0.0              101409.08   
3       197106.76          CNY                   0.0              197106.76   
4       101536.00          CNY                   0.0              101536.00   

   fin_ccy_ncp_os_amt  fin_ccy_cp_os_amt  fin_ccy_amt  os_ccy_amt    fin_date  \
0                 0.0                0.0    113268.50         0.0  2017-03-25   
1                 0.0                0.0    106717.15         0.0  2017-03-11   
2                 0.0                0.0    101409.08         0.0  2017-04-10   
3                 0.0                0.0    197106.76         0.0  2017-04-10   
4                 0.0                0.0    101536.00         0.0  2017-04-10   

  sale_ledger_flag pool_based_flag step_code product_variant_code  rel_seq_no  \
0                Y               N      SETT               IFNB02        37.0   
1                Y               N      SETT               IFNB02        29.0   
2                Y               N      SETT               IFNB02       116.0   
3                Y               N      SETT               IFNB02       116.0   
4                Y               N      SETT               IFNB02       116.0   

    pymt_date settled_flag  late_days  finance_days  finance_due_days  isLate  \
0  2017-05-04            Y          0            40                44       0   
1  2017-04-09            Y          0            29                44       0   
2  2017-09-18            Y        158           161                 3       1   
3  2017-09-18            Y        158           161                 3       1   
4  2017-09-18            Y        158           161                 3       1   

   late_days_bucket  fin_xrate  pymt_xrate  doc_xrate    doc_usd_amt  \
0                 0   1.000000    1.000000   1.000000  113268.500000   
1                 0   1.000000    1.000000   1.000000  106717.150000   
2                 2   0.145113    0.152346   0.144957   14699.950219  

In [7]:
#check for columns with missing values:

na_cols = data.columns[data.isnull().any()]
na_cols

Index([u'fin_tenor', u'to_seq_no', u'rel_seq_no', u'le_id', u'lid_isic_cd_val',
       u'buyer_supplier_yrs', u'buyer_supplier_past_inv_cnt',
       u'buyer_supplier_annual_inv_cnt', u'buyer_supplier_ave_fin_amt',
       u'buyer_supplier_ave_annual_fin_amt', u'buyer_supplier_std_fin_amt',
       u'buyer_supplier_late_days', u'buyer_supplier_isLate',
       u'buyer_supplier_dr', u'buyer_supplier_term', u'buyer_supplier_cty',
       u'buyer_supplier_prevyr_inv_cnt', u'buyer_supplier_prevyr_ave_fin_amt',
       u'buyer_supplier_prevyr_std_fin_amt',
       u'buyer_supplier_prevyr_late_days', u'buyer_supplier_prevyr_isLate',
       u'buyer_supplier_prevyr_dr', u'buyer_supplier_prevyr_term',
       u'buyer_supplier_season_x', u'buyer_supplier_6m_inv_cnt',
       u'buyer_supplier_6m_ave_fin_amt', u'buyer_supplier_6m_std_fin_amt',
       u'buyer_supplier_6m_dr', u'buyer_supplier_6m_term',
       u'buyer_supplier_6m_late_days', u'buyer_supplier_6m_isLate',
       u'buyer_supplier_3m_inv_cnt', u

In [8]:
data_orig = data

In [9]:
print(len(data))
data['CG'] = np.where(data.CG=='no_CG','NO_CG', data.CG)
data = data[data.cty_code!='ZM']
print(len(data))

296621
296620


In [13]:
data['late_days_bucket'] = np.where(data.late_days>60, 3, np.where(data.late_days>30, 2,np.where(data.late_days>0,1,0)))

/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [23]:
data.to_csv(data_dir+'data_for_model.csv', index= False)

In [24]:
# change missing data:

for i in range(len(na_cols)):
    col = na_cols[i]
    data[col] = np.where(pd.isnull(data[col]),0,data[col])

data.describe()

/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


supplier_id      buyer_id   doc_ccy_amt          tenor   grace_period  \
count  2.966200e+05  2.966200e+05  2.966200e+05  296620.000000  296620.000000   
mean   1.002386e+08  1.002482e+08  1.075823e+06      57.219628       0.540759   
std    1.135223e+05  1.013389e+05  2.703325e+07      29.303963       5.963682   
min    1.000000e+08  1.000005e+08  1.400000e-01       0.000000       0.000000   
25%    1.002159e+08  1.001983e+08  8.175950e+02      30.000000       0.000000   
50%    1.002928e+08  1.003068e+08  1.369590e+04      45.000000       0.000000   
75%    1.003069e+08  1.003068e+08  5.777740e+04      90.000000       0.000000   
max    1.004228e+08  1.004310e+08  8.323897e+09     360.000000     158.000000   

           fin_tenor      to_seq_no    from_seq_no  pymt_alloc_amt  \
count  296620.000000  296620.000000  296620.000000    2.966200e+05   
mean       69.722429    6113.013671    5855.261934    1.076429e+06   
std        27.002664   15551.462645   15214.398217    2.702763e+07   
min         0.000000       0.000000       1.000000    1.000000e-02   
25%        51.000000      56.000000       1.000000    8.023775e+02   
50%        62.000000    3528.000000    3407.000000    1.358307e+04   
75%        92.000000    6314.000000    5830.000000    5.739198e+04   
max       360.000000   99314.000000   99312.000000    8.323897e+09   

       fin_ccy_cp_alloc_amt  fin_ccy_ncp_alloc_amt  fin_ccy_ncp_os_amt  \
count          2.966200e+05           2.966200e+05       296620.000000   
mean           2.512097e+05           8.243791e+05            1.854492   
std            4.776723e+06           2.660499e+07          178.535951   
min            0.000000e+00           0.000000e+00            0.000000   
25%            1.708700e+02           0.000000e+00            0.000000   
50%            2.608530e+03           0.000000e+00            0.000000   
75%            2.762716e+04           0.000000e+00            0.000000   
max            4.994590e+08           8.323897e+09        17189.910000   

       fin_ccy_cp_os_amt   fin_ccy_amt     os_ccy_amt     rel_seq_no  \
count      296620.000000  2.966200e+05  296620.000000  296620.000000   
mean           16.690425  1.075589e+06      18.544916    6113.013671   
std          1606.823559  2.702274e+07    1785.359510   15551.462645   
min             0.000000  1.300000e-01       0.000000       0.000000   
25%             0.000000  8.224125e+02       0.000000      56.000000   
50%             0.000000  1.387547e+04       0.000000    3528.000000   
75%             0.000000  5.906463e+04       0.000000    6314.000000   
max        154709.190000  8.323897e+09  171899.100000   99314.000000   

           late_days   finance_days  finance_due_days         isLate  \
count  296620.000000  296620.000000     296620.000000  296620.000000   
mean        3.901345      47.780558         44.548877       0.584698   
std         9.313471      25.102513         25.645531       0.492775   
min         0.000000       0.000000          0.000000       0.000000   
25%         0.000000      25.000000         22.000000       0.000000   
50%         1.000000      44.000000         41.000000       1.000000   
75%         5.000000      69.000000         66.000000       1.000000   
max       158.000000     270.000000        270.000000       1.000000   

       late_days_bucket      fin_xrate     pymt_xrate      doc_xrate  \
count     296620.000000  296620.000000  296620.000000  296620.000000   
mean           0.611806       0.463951       0.474425       0.473423   
std            0.557953       0.488360       0.490078       0.489019   
min            0.000000       0.000075       0.000075       0.000075   
25%            0.000000       0.029017       0.029033       0.029017   
50%            1.000000       0.030382       0.031337       0.030382   
75%            1.000000       1.000000       1.000000       1.000000   
max            3.000000       1.558917       1.557793       1.562907   

        doc_usd_amt   fin_usd_amt

In [15]:
for col in data.columns:
    print(col)

cty_code
doc_id
supplier_id
buyer_id
doc_type_code
deal_id
fin_flag
rec_id
doc_date
doc_ccy_code
doc_ccy_amt
tenor
tenor_start_date
due_date
grace_period
maturity_date
fin_tenor_start_date
fin_tenor
to_seq_no
from_seq_no
pymt_ccy_code
pymt_alloc_amt
fin_ccy_code
fin_ccy_cp_alloc_amt
fin_ccy_ncp_alloc_amt
fin_ccy_ncp_os_amt
fin_ccy_cp_os_amt
fin_ccy_amt
os_ccy_amt
fin_date
sale_ledger_flag
pool_based_flag
step_code
product_variant_code
rel_seq_no
pymt_date
settled_flag
late_days
finance_days
finance_due_days
isLate
late_days_bucket
fin_xrate
pymt_xrate
doc_xrate
doc_usd_amt
fin_usd_amt
os_usd_amt
pymt_usd_amt
dr
dr_bucket
product_
client_id
le_id
lid_isic_cd_val
industry_code
CG
buyer_supplier_yrs
buyer_supplier_past_inv_cnt
buyer_supplier_annual_inv_cnt
buyer_supplier_ave_fin_amt
buyer_supplier_ave_annual_fin_amt
buyer_supplier_std_fin_amt
buyer_supplier_late_days
buyer_supplier_isLate
buyer_supplier_dr
buyer_supplier_term
buyer_supplier_cty
buyer_supplier_prevyr_inv_cnt
buyer_supplier

In [16]:
feature_set = data[['cty_code', 
#'doc_id', 
# 'supplier_id', 
# 'buyer_id', 
# 'doc_type_code', 
# 'deal_id', 
# 'fin_flag', 
# 'rec_id', 
# 'doc_date', 
'doc_ccy_code', 
# 'doc_ccy_amt', 
'tenor', 
# 'tenor_start_date', 
# 'due_date', 
'grace_period', 
# 'maturity_date', 
# 'fin_tenor_start_date', 
'fin_tenor', 
# 'to_seq_no', 
# 'from_seq_no', 
'fin_ccy_code', 
# 'fin_ccy_cp_alloc_amt', 
# 'fin_ccy_ncp_alloc_amt', 
# 'fin_ccy_ncp_os_amt', 
# 'fin_ccy_cp_os_amt', 
# 'fin_ccy_amt', 
# 'os_ccy_amt', 
# 'pymt_ccy_amt', 
# 'dr', 
# 'fin_date', 
# 'sale_ledger_flag', 
# 'pool_based_flag', 
# 'step_code', 
'product_variant_code', 
# 'rel_seq_no', 
# 'pymt_date', 
# 'settled_flag', 
# 'late_days', 
# 'finance_days', 
# 'finance_due_days', 
# 'isLate', 
# 'late_days_bucket', 
# 'dr_bucket', 
'doc_usd_amt', 
# 'fin_usd_amt', 
# 'os_usd_amt', 
# 'pymt_usd_amt', 
'product_', 
# 'fin_rate', 
'due_date_dow', 
'maturity_date_dow', 
'buyer_centric_flag', 
'CG', 
'ccy_wk_vol', 
'ccy_3m_vol', 
'ccy_6m_vol', 
'ccy_yr_vol', 
'ccy_tenor_vol', 
'ccy_fintenor_vol', 
'ccy_wk_vector', 
'ccy_3m_vector', 
'ccy_6m_vector', 
'ccy_yr_vector', 
'ccy_tenor_vector', 
'ccy_fintenor_vector', 
'RICI_index', 
# 'test_split', 
'buyer_supplier_prevyr_inv_cnt', 
'buyer_supplier_prevyr_ave_fin_amt', 
'buyer_supplier_prevyr_std_fin_amt', 
'buyer_supplier_prevyr_late_days', 
# 'buyer_supplier_prevyr_isLate', 
'buyer_supplier_prevyr_dr', 
'buyer_supplier_prevyr_term', 
'buyer_supplier_season_x', 
'buyer_supplier_yrs', 
'buyer_supplier_past_inv_cnt', 
'buyer_supplier_annual_inv_cnt', 
'buyer_supplier_ave_fin_amt', 
'buyer_supplier_ave_annual_fin_amt', 
'buyer_supplier_std_fin_amt', 
'buyer_supplier_late_days', 
#'buyer_supplier_isLate', 
# 'buyer_supplier_dr', 
'buyer_supplier_term', 
'buyer_supplier_cty', 
'buyer_supplier_3m_inv_cnt', 
'buyer_supplier_3m_ave_fin_amt', 
'buyer_supplier_3m_std_fin_amt', 
# 'buyer_supplier_3m_dr', 
'buyer_supplier_3m_term', 
'buyer_supplier_3m_late_days', 
# 'buyer_supplier_3m_isLate', 
'buyer_supplier_6m_inv_cnt', 
'buyer_supplier_6m_ave_fin_amt', 
'buyer_supplier_6m_std_fin_amt', 
# 'buyer_supplier_6m_dr', 
'buyer_supplier_6m_term', 
'buyer_supplier_6m_late_days', 
# 'buyer_supplier_6m_isLate', 
'client_yrs', 
'client_past_inv_cnt', 
'client_annual_inv_cnt', 
'client_ave_fin_amt', 
'client_ave_annual_fin_amt', 
'client_std_fin_amt', 
'client_late_days', 
# 'client_isLate', 
'client_dr', 
'client_term', 
'client_cty', 
'client_prevyr_inv_cnt', 
'client_prevyr_ave_fin_amt', 
'client_prevyr_std_fin_amt', 
'client_prevyr_late_days', 
# 'client_prevyr_isLate', 
# 'client_prevyr_dr', 
'client_prevyr_term', 
'client_season_x', 
'client_6m_inv_cnt', 
'client_6m_ave_fin_amt', 
'client_6m_std_fin_amt', 
# 'client_6m_dr', 
'client_6m_term', 
'client_6m_late_days', 
# 'client_6m_isLate', 
'client_3m_inv_cnt', 
'client_3m_ave_fin_amt', 
'client_3m_std_fin_amt', 
# 'client_3m_dr', 
'client_3m_term', 
'client_3m_late_days', 
# 'client_3m_isLate', 
# 'first_client_invoice', 
# 'client_id', 
'industry_code'                    ]]

uncast_cols = feature_set.columns

In [17]:
feature_set1=pd.get_dummies(feature_set)
feature_set1.rename(columns = {x:x.replace("__","_") for x in feature_set1 if "__" in x}, inplace = True)
feature_set1.columns

Index([u'tenor', u'grace_period', u'fin_tenor', u'doc_usd_amt',
       u'due_date_dow', u'maturity_date_dow', u'buyer_centric_flag',
       u'ccy_wk_vol', u'ccy_3m_vol', u'ccy_6m_vol',
       ...
       u'CG_5B', u'CG_6A', u'CG_6B', u'CG_7A', u'CG_7B', u'CG_8A', u'CG_8B',
       u'CG_9A', u'CG_9B', u'CG_NO_CG'],
      dtype='object', length=168)

In [18]:
feature_cols1 = [col for col in feature_set1.columns]
len(feature_cols1)

168

In [19]:
cast_frame = pd.read_csv(data_dir+'cast_columns_template.csv')
cast_frame.tail()

Empty DataFrame
Columns: [tenor, grace_period, fin_tenor, doc_usd_amt, due_date_dow, maturity_date_dow, buyer_centric_flag, ccy_wk_vol, ccy_3m_vol, ccy_6m_vol, ccy_yr_vol, ccy_tenor_vol, ccy_fintenor_vol, ccy_wk_vector, ccy_3m_vector, ccy_6m_vector, ccy_yr_vector, ccy_tenor_vector, ccy_fintenor_vector, RICI_index, buyer_supplier_prevyr_inv_cnt, buyer_supplier_prevyr_ave_fin_amt, buyer_supplier_prevyr_std_fin_amt, buyer_supplier_prevyr_late_days, buyer_supplier_prevyr_dr, buyer_supplier_prevyr_term, buyer_supplier_season_x, buyer_supplier_yrs, buyer_supplier_past_inv_cnt, buyer_supplier_annual_inv_cnt, buyer_supplier_ave_fin_amt, buyer_supplier_ave_annual_fin_amt, buyer_supplier_std_fin_amt, buyer_supplier_late_days, buyer_supplier_term, buyer_supplier_cty, buyer_supplier_3m_inv_cnt, buyer_supplier_3m_ave_fin_amt, buyer_supplier_3m_std_fin_amt, buyer_supplier_3m_term, buyer_supplier_3m_late_days, buyer_supplier_6m_inv_cnt, buyer_supplier_6m_ave_fin_amt, buyer_supplier_6m_std_fin_amt, buyer_supplier_6m_term, buyer_supplier_6m_late_days, client_yrs, client_past_inv_cnt, client_annual_inv_cnt, client_ave_fin_amt, client_ave_annual_fin_amt, client_std_fin_amt, client_late_days, client_dr, client_term, client_cty, client_prevyr_inv_cnt, client_prevyr_ave_fin_amt, client_prevyr_std_fin_amt, client_prevyr_late_days, client_prevyr_term, client_season_x, client_6m_inv_cnt, client_6m_ave_fin_amt, client_6m_std_fin_amt, client_6m_term, client_6m_late_days, client_3m_inv_cnt, client_3m_ave_fin_amt, client_3m_std_fin_amt, client_3m_term, client_3m_late_days, industry_code, cty_code_AE, cty_code_BD, cty_code_CN, cty_code_DF, cty_code_GB, cty_code_HK, cty_code_ID, cty_code_IN, cty_code_JO, cty_code_JP, cty_code_KE, cty_code_LK, cty_code_MO, cty_code_MY, cty_code_NG, cty_code_PH, cty_code_PK, cty_code_QA, cty_code_SG, cty_code_SP, cty_code_TH, cty_code_TW, cty_code_TZ, cty_code_UG, cty_code_US, cty_code_VN, cty_code_ZA, ...]
Index: []

In [ ]:
[x for x in feature_cols1 if x not in cast_frame.columns]

In [20]:
for col in cast_frame.columns:
    if col not in feature_set1.columns:
        feature_set1[col] = [0 for i in range(len(feature_set1))]
        
[x for x in cast_frame.columns if x not in feature_set1.columns], len(feature_set1.columns)

([], 210)

In [21]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

from sklearn.externals import joblib


In [22]:
# scale, joblib scaler
scaler = joblib.load(data_dir+'minmaxscaler_180223.pkl')
feature_set1=scaler.fit_transform(feature_set1)
type(feature_set1)


/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


numpy.ndarray

In [29]:
final =data
final.index = range(len(final))
final['rownum'] = final.index

/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [25]:
from sklearn.metrics import confusion_matrix as cm

In [26]:
rf = joblib.load(data_dir+'rf_ld_180223.joblib')

/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [27]:
rf.n_features_

210

In [30]:
### round,3
ld_pred= rf.predict(feature_set1)
ld_rf_prob = rf.predict_proba(feature_set1)

ld_rf_preds = [[final.doc_id[i], final.late_days_bucket[i], ld_pred[i], ld_rf_prob[i][0], 
                    ld_rf_prob[i][1], ld_rf_prob[i][2],ld_rf_prob[i][3]] for i in range(len(final))]

ld_rf_preds = pd.DataFrame(ld_rf_preds, columns = ['doc_id', 'late_days_bucket', 'isLate_predict', 'late_prob_0', 'late_prob_1', 
                                                   'late_prob_2', 'late_prob_3'])

ld_rf_preds.to_csv(data_dir+'ld_rf_preds.csv')

ld_rf_preds.head()

doc_id  late_days_bucket  isLate_predict  late_prob_0  \
0  RFHLM9WX4V-89034                 0               0          0.5   
1  V5HKSF85PW-36933                 0               0          1.0   
2   52HNXCS9NQ-6901                 3               1          0.1   
3   52HNXCS9NQ-6902                 3               1          0.1   
4   52HNXCS9NQ-6968                 3               3          0.1   

   late_prob_1  late_prob_2  late_prob_3  
0          0.3          0.1          0.1  
1          0.0          0.0          0.0  
2          0.5          0.2          0.2  
3          0.5          0.2          0.2  
4          0.1          0.0          0.8

In [31]:
print(cm(data.late_days_bucket, ld_pred))
print(cm(data.late_days_bucket, ld_pred)*1./(len(data)*1.))
print(accuracy_score(data.late_days_bucket, ld_pred))

[[93767 29033   145   242]
 [70826 92486   800  4186]
 [  968   879    24   358]
 [ 1711    10     0  1185]]
[[  3.16118266e-01   9.78794417e-02   4.88840941e-04   8.15858674e-04]
 [  2.38776886e-01   3.11799609e-01   2.69705347e-03   1.41123323e-02]
 [  3.26343470e-03   2.96338750e-03   8.09116041e-05   1.20693143e-03]
 [  5.76832311e-03   3.37131684e-05   0.00000000e+00   3.99501045e-03]]
0.631993796777


### DR

In [32]:

print("RF")

rf = joblib.load(data_dir+'rf_dr_180223.joblib')

dr_pred= rf.predict(feature_set1)
dr_rf_prob = rf.predict_proba(feature_set1)

dr_rf_preds = [[final.doc_id[i], final.late_days_bucket[i], dr_pred[i], dr_rf_prob[i][0], 
                    dr_rf_prob[i][1], dr_rf_prob[i][2]] for i in range(len(final))]

dr_rf_preds = pd.DataFrame(dr_rf_preds, columns = ['doc_id', 'dr_bucket', 'dr_predict', 'dr_prob_0', 'dr_prob_1', 
                                                   'dr_prob_2'])

dr_rf_preds.to_csv(data_dir+'dr_rf_preds.csv')

print(cm(data.dr_bucket, dr_pred))
dr_rf_preds.head()

RF
[[206688  23137  15228]
 [ 20237  22055   4282]
 [  3505    453   1035]]


doc_id  dr_bucket  dr_predict  dr_prob_0  dr_prob_1  dr_prob_2
0  RFHLM9WX4V-89034          0           1        0.3        0.4        0.3
1  V5HKSF85PW-36933          0           1        0.2        0.5        0.3
2   52HNXCS9NQ-6901          3           1        0.1        0.7        0.2
3   52HNXCS9NQ-6902          3           1        0.2        0.7        0.1
4   52HNXCS9NQ-6968          3           2        0.4        0.1        0.5

In [33]:
[x*1./len(data)*1. for x in cm(data.dr_bucket, dr_pred)]

[array([ 0.69681073,  0.07800216,  0.05133841]),
 array([ 0.06822534,  0.07435439,  0.01443598]),
 array([ 0.01181647,  0.00152721,  0.00348931])]

### 

In [34]:
cm(data.dr_bucket, dr_pred)*1./(len(data)*1.)

array([[ 0.69681073,  0.07800216,  0.05133841],
       [ 0.06822534,  0.07435439,  0.01443598],
       [ 0.01181647,  0.00152721,  0.00348931]])

In [35]:
accuracy_score(data.dr_bucket, dr_pred)

0.77465444002427353

In [36]:
!zip /home/flowcast/data/python/data_validate_180315/validate_preds.zip /home/flowcast/data/python/data_validate_180315/dr_rf_preds.csv /home/flowcast/data/python/data_validate_180315/ld_rf_preds.csv

  adding: home/flowcast/data/python/data_validate_180315/dr_rf_preds.csv (deflated 86%)
  adding: home/flowcast/data/python/data_validate_180315/ld_rf_preds.csv (deflated 87%)


In [37]:
len(data)

296620

In [38]:
data.ix[:196620]

/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


cty_code            doc_id  supplier_id     buyer_id doc_type_code  \
0            AE  RFHLM9WX4V-89034    100369293  100244505.0           INV   
1            AE  V5HKSF85PW-36933    100369293  100244505.0           INV   
2            CN   52HNXCS9NQ-6901    100399400  100310713.0           INV   
3            CN   52HNXCS9NQ-6902    100399400  100310713.0           INV   
4            CN   52HNXCS9NQ-6968    100399400  100310713.0           INV   
5            CN  HSHKT118NJ-19267    100336220  100328923.0           INV   
6            CN  SNHZ85QDCY-72538    100384003  100310713.0           INV   
7            CN  SNHZ85QDCY-72539    100384003  100310713.0           INV   
8            CN  SNHZ85QDCY-75968    100356120  100310713.0           INV   
9            CN  SNHZ85QDCY-76656    100356120  100310713.0           INV   
10           CN     WPHQFYB8MT-11    100336226  100328923.0           INV   
11           HK  13HKGVC8MC-25840    100241252  100015943.0           INV   
12           HK  13HKGVC8MC-26027    100241252  100015943.0           INV   
13           HK  13HKGVC8MC-27163    100396941  100015943.0           INV   
14           HK  13HKGVC8MC-27165    100396941  100015943.0           INV   
15           HK  13JFPJH5PW-12088    100118499  100015943.0           INV   
16           HK  18HSXZJQ19-18091    100041645  100015943.0           INV   
17           HK  19JCGMLB64-42937    100118497  100015943.0           INV   
18           HK  1FJKXPFYTL-15056    100118499  100015943.0           INV   
19           HK  1FJKXPFYTL-21181    100041645  100015943.0           INV   
20           HK  1MHPJJ7ZSB-46755    100041645  100015943.0           INV   
21           HK  1MHPJJ7ZSB-64766    100241252  100015943.0           INV   
22           HK  1WHKC48B6B-66763    100241252  100015943.0           INV   
23           HK  1WHKC48B6B-67547    100241252  100015943.0           INV   
24           HK  1WHKC48B6B-67787    100118497  100015943.0           INV   
25           HK  1WHKC48B6B-68059    100396941  100015943.0           INV   
26           HK  1YHQRTQTYD-81701    100041645  100015943.0           INV   
27           HK  1ZHRLNGFW1-78825    100118499  100015943.0           INV   
28           HK  1ZHRLNGFW1-79094    100041645  100015943.0           INV   
29           HK  21J4RVPN54-19328    100118499  100015943.0           INV   
...         ...               ...          ...          ...           ...   
196591       US  B7HWBN5BKJ-20344    100306891  100306803.0           INV   
196592       US  B7HWBN5BKJ-20345    100306891  100306803.0           INV   
196593       US  B7HWBN5BKJ-20346    100306891  100306803.0           INV   
196594       US  B7HWBN5BKJ-20347    100306891  100306803.0           INV   
196595       US  B7HWBN5BKJ-20350    100306891  100306803.0           INV   
196596       US  B7HWBN5BKJ-20351    100306891  100306803.0           INV   
196597       US  B7HWBN5BKJ-20352    100306891  100306803.0           INV   
196598       US  B7HWBN5BKJ-20353    100306891  100306803.0           INV   
196599       US  B7HWBN5BKJ-20356    100306891  100306803.0           INV   
196600       US  B7HWBN5BKJ-20357    100306891  100306803.0           INV   
196601       US  B7HWBN5BKJ-20358    100306891  100306803.0           INV   
196602       US  B7HWBN5BKJ-20359    100306891  100306803.0           INV   
196603       US  B7HWBN5BKJ-20362    100306891  100306803.0           INV   
196604       US  B7HWBN5BKJ-20363    100306891  100306803.0           INV   
196605       US  B7HWBN5BKJ-20364    100306891  100306803.0           INV   
196606       US  B7HWBN5BKJ-20365    100306891  100306803.0           INV   
196607       US  B7HWBN5BKJ-20368    100306891  100306803.0           INV   
196608       US  B7HWBN5BKJ-20369    100306891  100306803.0           INV   
196609       US  B7HWBN5BKJ-20370    100306891  100306803.0           INV   
196610       US  B7HWBN5BKJ-20371    100306891  100306803.0           INV   
196

In [40]:
data.ix[196620:196622]

cty_code            doc_id  supplier_id     buyer_id doc_type_code  \
196620       US  B7HWBN5BKJ-20387    100306891  100306803.0           INV   
196621       US  B7HWBN5BKJ-20388    100306891  100306803.0           INV   
196622       US  B7HWBN5BKJ-20389    100306891  100306803.0           INV   

           deal_id fin_flag      rec_id    doc_date doc_ccy_code  doc_ccy_amt  \
196620  TF777R0069        Y  7035190704  2017-05-20          USD       266.78   
196621  TF777R0069        Y  7035190702  2017-05-20          USD       373.66   
196622  TF777R0069        Y  7035190700  2017-05-20          USD       383.86   

        tenor     tenor_start_date    due_date  grace_period maturity_date  \
196620     90  2017-05-20 00:00:00  2017-08-18             0    2017-08-24   
196621     90  2017-05-20 00:00:00  2017-08-18             0    2017-08-24   
196622     90  2017-05-20 00:00:00  2017-08-18             0    2017-08-24   

       fin_tenor_start_date  fin_tenor  to_seq_no  from_seq_no pymt_ccy_code  \
196620  2017-05-20 00:00:00       96.0     6429.0         5810           USD   
196621  2017-05-20 00:00:00       96.0     6429.0         5810           USD   
196622  2017-05-20 00:00:00       96.0     6429.0         5810           USD   

        pymt_alloc_amt fin_ccy_code  fin_ccy_cp_alloc_amt  \
196620          266.78          USD                266.78   
196621          373.66          USD                373.66   
196622          383.86          USD                383.86   

        fin_ccy_ncp_alloc_amt  fin_ccy_ncp_os_amt  fin_ccy_cp_os_amt  \
196620                    0.0                 0.0                0.0   
196621                    0.0                 0.0                0.0   
196622                    0.0                 0.0                0.0   

        fin_ccy_amt  os_ccy_amt    fin_date sale_ledger_flag pool_based_flag  \
196620       266.78         0.0  2017-05-26                Y               N   
196621       373.66         0.0  2017-05-26                Y               N   
196622       383.86         0.0  2017-05-26                Y               N   

       step_code product_variant_code  rel_seq_no   pymt_date settled_flag  \
196620      SETT               RSRV01      6429.0  2017-08-24            Y   
196621      SETT               RSRV01      6429.0  2017-08-24            Y   
196622      SETT               RSRV01      6429.0  2017-08-24            Y   

        late_days  finance_days  finance_due_days  isLate  late_days_bucket  \
196620          6            90                84       1                 1   
196621          6            90                84       1                 1   
196622          6            90                84       1                 1   

        fin_xrate  pymt_xrate  doc_xrate  doc_usd_amt  fin_usd_amt  \
196620        1.0         1.0        1.0       266.78       266.78   
196621        1.0         1.0        1.0       373.66       373.66   
196622        1.0         1.0        1.0       383.86       383.86   

        os_usd_amt  pymt_usd_amt   dr  dr_bucket product_  client_id  \
196620         0.0        266.78  0.0          0     RSRV  100306891   
196621         0.0        373.66  0.0          0     RSRV  100306891   
196622         0.0        383.86  0.0          0     RSRV  100306891   

             le_id  lid_isic_cd_val  industry_code  CG  buyer_supplier_yrs  \
196620  13374205.0           8342.0             83  6B                 1.0   
196621  13374205.0           8342.0             83  6B                 1.0   
196622  13374205.0           8342.0             83  6B                 1.0   

        buyer_supplier_past_inv_cnt  buyer_supplier_annual_inv_cnt  \
196620                      90979.0                        90979.0   
196621                      90979.0                        90979.0   
196622                      90979.0                        90979.0   

        buyer_supplier_ave_fin_amt  buyer_supplier_ave_annual_fin_amt  \
196620           

In [41]:
data1 = data.ix[:196620]
data2 = data.ix[196621:]
len(data1), len(data2), len(data1)+len(data2), len(data)

(196621, 99999, 296620, 296620)

In [42]:
data1.to_csv(data_dir+'data_for_model1.csv', index= False)
data2.to_csv(data_dir+'data_for_model2.csv', index= False)

In [43]:
!zip /home/flowcast/data/python/data_validate_180315/data_for_model1.zip /home/flowcast/data/python/data_validate_180315/data_for_model1.csv

  adding: home/flowcast/data/python/data_validate_180315/data_for_model1.csv (deflated 91%)


In [44]:
!zip /home/flowcast/data/python/data_validate_180315/data_for_model2.zip /home/flowcast/data/python/data_validate_180315/data_for_model2.csv

  adding: home/flowcast/data/python/data_validate_180315/data_for_model2.csv (deflated 94%)


In [45]:
scaled_df = pd.DataFrame(data = feature_set1, columns=cast_frame.columns)
scaled_df.tail()

tenor  grace_period  fin_tenor  doc_usd_amt  due_date_dow  \
296615  0.097222           0.0   0.180556     0.000166      0.166667   
296616  0.097222           0.0   0.180556     0.000172      0.166667   
296617  0.097222           0.0   0.186111     0.000165      0.500000   
296618  0.083333           0.0   0.172222     0.000135      0.500000   
296619  0.083333           0.0   0.172222     0.000283      0.500000   

        maturity_date_dow  buyer_centric_flag  ccy_wk_vol  ccy_3m_vol  \
296615                0.5                 0.0         0.0         0.0   
296616                0.5                 0.0         0.0         0.0   
296617                0.0                 0.0         0.0         0.0   
296618                0.0                 0.0         0.0         0.0   
296619                0.0                 0.0         0.0         0.0   

        ccy_6m_vol  ccy_yr_vol  ccy_tenor_vol  ccy_fintenor_vol  \
296615         0.0         0.0            0.0               0.0   
296616         0.0         0.0            0.0               0.0   
296617         0.0         0.0            0.0               0.0   
296618         0.0         0.0            0.0               0.0   
296619         0.0         0.0            0.0               0.0   

        ccy_wk_vector  ccy_3m_vector  ccy_6m_vector  ccy_yr_vector  \
296615       0.085615       0.003933       0.003609       0.003328   
296616       0.085615       0.003933       0.003609       0.003328   
296617       0.085615       0.003933       0.003609       0.003328   
296618       0.085615       0.003933       0.003609       0.003328   
296619       0.085615       0.003933       0.003609       0.003328   

        ccy_tenor_vector  ccy_fintenor_vector  RICI_index  \
296615           0.00313              0.00313    0.914044   
296616           0.00313              0.00313    0.914044   
296617           0.00313              0.00313    0.914132   
296618           0.00313              0.00313    0.914044   
296619           0.00313              0.00313    0.914044   

        buyer_supplier_prevyr_inv_cnt  buyer_supplier_prevyr_ave_fin_amt  \
296615                       0.000429                           0.000262   
296616                       0.000429                           0.000262   
296617                       0.000459                           0.000263   
296618                       0.000229                           0.000363   
296619                       0.000160                           0.000480   

        buyer_supplier_prevyr_std_fin_amt  buyer_supplier_prevyr_late_days  \
296615                           0.000157                         0.172798   
296616                           0.000157                         0.172798   
296617                           0.000152                         0.173386   
296618                           0.000356                         0.176285   
296619                           0.000456                         0.166288   

        buyer_supplier_prevyr_dr  buyer_supplier_prevyr_term  \
296615                  0.137867                    0.175775   
296616                  0.137867                    0.175775   
296617                  0.137867                    0.176087   
296618                  0.137867                    0.167874   
296619                  0.137867                    0.159549   

        buyer_supplier_season_x  buyer_supplier_yrs  \
296615             6.500188e-07                 1.0   
296616             6.756088e-07                 1.0   
296617             6.455706e-07                 1.0   
296618             3.806731e-07                 1.0   
296619             6.045130e-07                 1.0   

        buyer_supplier_past_inv_cnt  buyer_supplier_annual_inv_cnt  \
296615                     0.000292                       0.000292   
296616                     0.000292                       0.000292   
296617                     0.000312                       0.000312   
296618                    

In [46]:
scaled_df.ix[:150000].to_csv(data_dir+'scaled_data1.csv', index= False)
scaled_df.ix[150001:].to_csv(data_dir+'scaled_data2.csv', index= False)

/data/flowcast/data/software/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [47]:
!zip /home/flowcast/data/python/data_validate_180315/scaled_data1.zip /home/flowcast/data/python/data_validate_180315/scaled_data1.csv

  adding: home/flowcast/data/python/data_validate_180315/scaled_data1.csv (deflated 94%)


In [48]:
!zip /home/flowcast/data/python/data_validate_180315/scaled_data2.zip /home/flowcast/data/python/data_validate_180315/scaled_data2.csv

  adding: home/flowcast/data/python/data_validate_180315/scaled_data2.csv (deflated 96%)
